### ISSUE TITLE
Stuck on "Locating server" in game

### ISSUE THREAD

**Issue by E34rrsff** [TheRemote/MinecraftBedrockServer#110]
I've tried using different devices to connect to the server, and they all get stuck on "Locating server."

**Comment by TheRemote** [comment]
Is this on Raspberry Pi or ARM devices as the server?

If so you may want to read https://jamesachambers.com/official-minecraft-bedrock-dedicated-server-on-raspberry-pi/ because it has to use emulation on ARM so this is expected.

A much better version to run on the Pi is the Java version which I have a script for here:  https://jamesachambers.com/raspberry-pi-minecraft-server-script-with-startup-service/

I've never seen this happen on a x86_64/amd64 box before so I assume this is an ARM device.  Can you confirm?

**Comment by E34rrsff** [comment]
Yeah, it is an ARM device, and I just remembered it's also 32-bit... there isn't any way for me to run a Bedrock server on it, right? I only have Bedrock edition so that's why I chose this.

**Comment by TheRemote** [comment]
Great question.  So basically no.  The issue is that the bedrock_server binary is built by Microsoft.  It's a statically built binary built for x86_64.  It won't run on 32 bit architecture or the ARM architecture without emulation.

Microsoft releasing ARM binaries would instantly solve the issue.  Bedrock is native C++ code so when they build that type of a binary it's just a big "blob" of static code and works a lot different than something like the Java version.  

I would say it's just a little too slow but maybe the Raspberry Pi 5 will do it.  When I wrote it it was completely unplayable.  Originally you could not even log in if you tried 100 times.  Now people can log in and it kind of actually works but monsters move in slow motion and block breaking is laggy, etc.  

I think the Raspberry Pi 5 (or another major revision or two of QEMU, the emulation software that makes running this at all possible even at a slow speed) will do it.  Hopefully that helps!

**Comment by E34rrsff** [comment]
Ok, thanks for the help
