### ISSUE TITLE
Start.sh bug on Debian while executing on non-root user

### ISSUE THREAD

**Issue by LookedPath** [TheRemote/MinecraftBedrockServer#120]
Hello,
if you execute the start.sh script with a non-root user the /sbin/route command won't be found and so the startup procedure won't continue.
This is because /sbin is not in the path of non root users.
You should consider using an alternative method to check for an internet connection or adding /sbin to the path if it's not already present.

**Comment by TheRemote** [comment]
Hello,

Thanks for reminding me of this.  Someone let me know on my web site that this was indeed still a thing.  I believe this issue is specific to Debian.  I used to have the path hard coded to get around the Debian issue but what ended up happening is that some other flavors didn't have the route binary on the /sbin path.

Because I've been on both sides of this problem at different times I coded a solution for both like this:

```
if [ -e '/sbin/route' ]; then
    DefaultRoute=$(/sbin/route -n | awk '$4 == "UG" {print $2}')
else
    DefaultRoute=$(route -n | awk '$4 == "UG" {print $2}')
fi
```

It's a little bit more hacky than I usually like to do but this issue has a bit of history on here and this should take care of both scenarios.  Thank you!

**Comment by LookedPath** [comment]
Yeah I believe this is an issue with just Debian as I haven't seen it happen on any other distro.
I manually solved my issue by adding /sbin to the path of the user that launches the server and by launching again the setup script, that added /sbin to the path and it started working again.
Making a script that works on multiple platforms must be a nightmare, thank you for the quick response and the quick fix.
