### ISSUE TITLE
run inside chroot jail?

### ISSUE THREAD

**Issue by apiskors** [TheRemote/MinecraftBedrockServer#121]
Hi, have you considered running Minecraft inside a chroot jail?
Or some other method to increase security, beyond the obvious part of running everything in its own "minecraft" Linux account?
I'm setting up a personal Minecraft Bedrock server right now, so I'd love to hear your thoughts on this...

**Comment by apiskors** [comment]
James, AFAICT your default MinecraftBedrockServer script setup does not use use Docker at all, just traditional Unix/Linux stuff.  Although I see now that you DO also offer a Docker containerized version.  I wasn't planning on using Docker at all.  My impression is that chroot is supposed to be simpler more efficient than Docker or other containers; but I lack experience with them.  Are you recommending Docker INSTEAD of chroot?

**Comment by TheRemote** [comment]
Ugh!  My bad.  I thought this was the Bedrock container.  Sorry about that!  You're right for sure as for the past couple of days I had issues opened on the Bedrock container and assumed this was that (and it was the first thing I read this morning).

So this is absolutely possible.  It would require creating an entire separate operating system on the disk for the chroot jail.  It's essentially exactly the same as a Docker container to be honest.  Docker also has an entire separate operating system / image installed that the chroot jail runs in.

These are tricky to set up and there are security issues with them if it isn't done exactly right.  Here is how you would create a chroot with Ubuntu:  https://packaging.ubuntu.com/html/chroots.html.  You use debootstrap which will download and install a base copy of Ubuntu.  This is basically a OS inside an OS (very similar to both virtualization and Docker).  

Look at this step to see why this probably isn't a great approach:

$ sudo mount -t none -o bind /tmp trusty/tmp
$ xhost +
Some programs may need you to bind /dev or /proc.

You need to share your /tmp folder and potentially even the /bind and /proc folder of the host OS with the container for this to work.  That is not a good idea at all especially the proc folder and other ones.  I am certain this would be *less* secure than using just the regular minecraft account approach and not having them in the sudoers group.

If the minecraft account is breached and it is not in the sudoers group and it doesn't have access to any files outside of it's home directory that is honestly ideal.  It's like when people hack web servers and have access to the www-data user.  If there isn't stuff to do inside the /var/www/html folder this is essentially worthless.  It happens all the time and it's the first line of defense on Linux for sure (and very disappointing to attackers).  This makes lateral movement extremely difficult or potentially impossible. 

So to answer your question about whether I would use Docker over the standalone version my answer would probably be no.  Running it as a non-privileged user will give you multiple layers of security that attackers are not going to bother defeating all of them.  They will just move on to another target that is just running it as root rather than try to defeat your additional security that almost nobody else will even have on there (because this has never happened).

That's not to say it can't happen.  It just happened on Java.  It is a once every 5-10 year hack that happened on Java (and log4j was *way* bigger than Minecraft and was attacking things a lot more important through this exploit).  If it did happen though unless you are being individually targeted (meaning you have an extremely popular server or extremely dangerous enemies) then it's simply not going to be worth it to continue attacking you vs. move to the next server on the list on Shodan/Censys.

I would always take Docker over the chroot jail though.  Docker is basically a chroot jail with a lot more security and features added on top of it but it works essentially the same.  It's actually even better because you can run the 64 bit container on ARM and other platforms and it functions essentially this way still.

Containerization is considered more secure across the board so if you have reason to believe you are going to be targeted beyond the norm of bots attacking servers with old exploits to see who hasn't patched / secured their setup then yes I would say this would be more secure than a chroot jail and if you don't run Docker as root it's an additional security layer / more secure than the standalone version as well.

Sorry about confusing which project I'm in, although I'm glad we covered some of the Docker stuff because it did tie into this answer a little bit.  I would say you will find Docker to be much simpler than setting up a chroot jail (check out the Ubuntu link above to see what I mean).  It's basically a one liner to run the containerized version of it.

Thanks for asking this and sorry my answer was so long.  You are not going to be the only one to answer this question and I'll probably have smoother answers for this later (or at least less verbose).  It's always a challenging question how to secure these.  In my opinion from the questions you are asking I think the Docker version not running as root will meet the security requirements you've outlined here and it should be a one-liner to set it up.  

Hopefully that helps and let me know if I can clarify anything!

**Comment by apiskors** [comment]
Right now, before I get to more complicated stuff like chroot or Docker, I'm working on just getting bedrock_server to run as its own "mc" Linux user.  I'm surprised to see that your SetupMinecraft.sh script seems to assume that the user we want running bedrock_server, is the SAME as the user installing things by running SetupMinecraft.sh, who of course MUST have sudo!  Am I overlooking some option to configure it to run as its own separate user?

So far I've made some obvious hacks to the "start.sh" and "/etc/systemd/system/mc-*.service" scripts to make them work when run with "sudo -u mc".  Of course I hit file permission problems at first.  But once I fixed those, and used netstat to find (and kill) the zombie process that was blocking port 19132, it seems to work, yay!

But it seems really weird that your SetupMinecraft.sh has all its other fancy features, but DOESN'T handle running as a separte user on its own.  Which makes me think I might be missing something... 

Btw, I'm told that people sometimes run dynamic websites and other complicated things inside chroots, so I don't see why running bedrock_server inside one would be any more difficult.  "ldd bedrock_server | wc -l" says it depends on 13 shared libraries, while /bin/ls has 7.  So that doesn't sound TOO bad...  Sometime in the next couple weeks, I hope to experiment with using the Jailkit tools to set up a chroot for it.  Maybe I'll eventually try Docker too.

**Comment by TheRemote** [comment]
Hey apiskors,

Ahh, yes, that is a sticking point for sure.  This has come up a lot more on my blog than GitHub and I probably should add this to the documentation.  It looks like setting up users for other types of services as well and is a very similar process..

```
sudo adduser minecraft
sudo mkdir /home/minecraft
sudo usermod -d /home/minecraft minecraft
sudo adduser minecraft sudoers
```

Now log in or change contexts to that new user and run SetupMinecraft.sh again followed by:

`sudo deluser minecraft sudoers`

That should be about it although you can go further and set the suid bits on a lot of your executables so that the minecraft user can't even run the utilities in /usr/bin.  This is going very far but it will provide additional protection on a standalone version.

I think jailkit would be worth pursuing.  These are chroot containers that handle a lot of the pitfalls I was talking about in my really, really long post.  They will set up a lot of these mounts that have to be shared between the OS and the chroot container in a more secure way.  

It's all way harder than docker though.  Using the Docker version would be 3 lines on any platform as well as any architecture (including on Raspberry Pi and ARM devices):

```
sudo apt install docker.io
sudo docker container add myminecraft
docker run -it -v yourvolumename:/minecraft -p 19132:19132/udp -p 19132:19132 -p 19133:19133/udp -p 19133:19133 05jchambers/legendary-bedrock-container:latest
```

and that's it.  You now have a running Bedrock server in the background!  It's jailed through Docker basically.  The server files are available at:

`/var/lib/docker/volumes/`

and looks like this:

```
root@jamesgigabyte-linux:/var/lib/docker/volumes/minecraftbe/_data# ls
backups                       logs
bedrock_server                minecraftpe
bedrock_server_how_to.html    premium_cache
bedrock_server_symbols.debug  release-notes.txt
behavior_packs                resource_packs
Dedicated_Server.txt          server.properties
definitions                   structures
development_behavior_packs    treatments
development_resource_packs    valid_known_packs.json
development_skin_packs        worlds
downloads                     world_templates

```

Here you can see the docker volume's contents.  When running Docker all of your persistent data has to be stored in that volume.  If someone attacked it you would literally see the files they were writing to the disk in a theoretical attack.  They're in a jailed volume.  

They can't write to the base image (at least not persistently) and their changes would be lost upon restarting the container.  Basically in Docker the entire filesystem is *also* jailed to a Docker volume.  Otherwise their changes wouldn't persist anywhere and couldn't without exploiting Docker itself.  

I cannot imagine you setting up a chroot jail with any alterative to Docker easier than this but it may be able to be just as easy (like maybe 2-3 steps?).  I've heard of firejail though before.  If you try this definitely let me know if it ended up working pretty well / clean or if it ended up being clunkier.  I honestly don't know.

The bedrock_server executable is a statically linked binary for the most part (you pointed out some of the links that it has) but mostly it's a big "blob" binary.  That really helps, and it helped with developing the Docker container too for the same reason.  I agree it doesn't sound too bad.

I would definitely really encourage you to try the Docker version though.  I wouldn't push this as hard normally but it is *exactly* what you are trying to do and it works really well.  I resisted it for *years*.  All the calls in issues closed in here for me to finally make it.  When I did I couldn't believe it.  

I'm not sure I'm ready to say (or accept) it's better than the standalone version but because of a lot of the issues that came up in this thread and how much better the Docker version would fare in these theoretical attacks I think it's safe to say I'm closer to acceptance of that and even see some security benefits I wasn't really thinking about before. 

This is all theoretical.  There has never been an attack like this.  Again though I think it's worth investigating because a log4j for Bedrock could drop someday.  Anyone who says that is impossible I would definitely bet against on that one.  It's just very hard and it's never happened yet but it's probably only a matter of time before *something* is found at some point.

I want to leave this issue open if you don't mind (unless you end up not checking out this) as I'm curious to see what you find with that experience.  I definitely don't think everything works the best way it possibly could right now and am open to improvement.  Maybe the SetupMinecraft.sh script should be changed to literally ask them for a user to set it up as.  Theoretically it could even set up the user for them although this makes me nervous across different distros but it could be done (even some of the commands I posted above are Ubuntu/Debianish commands and may not work on other distros where you'd want to use something like usermod -aG).

**Comment by TheRemote** [comment]
Closing for now but definitely let me know if you tried this / what the results were!

**Comment by apiskors** [comment]
James, I never did try chroot, but I came up with some more restrictive SystemD security settings for Mojang's bedrock_server.  You can find them here:

https://github.com/apiskors/saprolith/blob/master/systemd/mcb%40.service

Btw, thanks for the work you put into your MinecraftBedrockServer project, it was quite helpful in getting me started running my own Minecraft server!

**Comment by TheRemote** [comment]
Looks good, thank you for sharing!
