### ISSUE TITLE
Add plugin support

### ISSUE THREAD

**Issue by OsoaGitHub** [TheRemote/MinecraftBedrockServer#20]
Hi,
If any of you have ever used Pocketmine, you will know you can get plugins. I understand it may not be possible to do this right now, but it would be great to get plugins for the dedicated server. Thanks!

**Comment by qq1737333652** [comment]
This project which used OFFICIAL Core doesn't support any plugins.Instead of this,it is Add-On,like mods.

**Comment by TheRemote** [comment]
Absolutely not possible with vanilla Bedrock, there are other solutions out there but they're usually several versions behind the main Bedrock edition!  This may change some day if something like Spigot / Bukkit is created for the C++ version but because of how differently they work that doesn't seem possible without cooperation from Microsoft.
