### ISSUE TITLE
There is no screen to be resumed matching minecraft. (Ubuntu 16.04.6 (LTS) x64)

### ISSUE THREAD

**Issue by kasperhartwich** [TheRemote/MinecraftBedrockServer#29]
On a brand new Ubuntu 16.04.6 (LTS) x64 instance (on Digital Ocean), the script ends with no screen and no minecraft server has been started:

> There is no screen to be resumed matching minecraft.

This is how the install script ends:

> Start Minecraft server at startup automatically (y/n)?y
> Created symlink from /etc/systemd/system/multi-user.target.wants/minecraft.service to /etc/systemd/system/minecraft.service.
> Your time zone is currently set to Etc/UTC.  Current system time: Tue Apr 14 11:13:37 UTC 2020
> You can adjust/remove the selected reboot time later by typing crontab -e or running SetupMinecraft.sh again.
> Automatically restart and backup server at 4am daily (y/n)?y
> no crontab for root
> Daily restart scheduled.  To change time or remove automatic restart type crontab -e
> Setup is complete.  Starting Minecraft server...
> Minecraft server failed to start after 20 seconds.
> There is no screen to be resumed matching minecraft.

**Comment by SixthTitan** [comment]
I had an issue like this before same exact error and what I did to resolve it was completely erase and reinstall Ubuntu. The issue is related to some of the dependencies. You don't want to install anything before running this sh script. Let it download the dependencies for you and use QEMU 3.1; this is how I fixed it. 

QEMU: http://ftp.us.debian.org/debian/pool/main/q/qemu/qemu-user-static_3.1+dfsg-8+deb10u5_arm64.deb

After doing that I got the server to run.
Hope this helps.
