### ISSUE TITLE
[NOT ISSUE] Questions

### ISSUE THREAD

**Issue by Lycol50** [TheRemote/MinecraftBedrockServer#32]
Is this repository will be updated if the new version of bedrock comes out?

**Comment by outforpublic** [comment]
The code automatically checks for updates every launch

**Comment by outforpublic** [comment]
BTW I think this repo is closed from inactivity.

**Comment by aghadjip** [comment]
yes, this code snippet does it, it exists in the main setup script and start.sh. If it gets moved or otherwise changes location, you may want to edit the start,sh if indeed this repo is closed 

 #Test internet connectivity first
wget --spider --quiet https://minecraft.net/en-us/download/server/bedrock/
if [ "$?" != 0 ]; then
    echo "Unable to connect to update website (internet connection may be down).  Skipping update ..."
else
    # Download server index.html to check latest version
    wget -O downloads/version.html https://minecraft.net/en-us/download/server/bedrock/
    DownloadURL=$(grep -o 'https://minecraft.azureedge.net/bin-linux/[^"]*' downloads/version.html)
    DownloadFile=$(echo "$DownloadURL" | sed 's#.*/##')

    # Download latest version of Minecraft Bedrock dedicated server if a new one is available
    if [ -f "downloads/$DownloadFile" ]
    then
        echo "Minecraft Bedrock server is up to date..."
    else
        echo "New version $DownloadFile is available.  Updating Minecraft Bedrock server ..."
        wget -O "downloads/$DownloadFile" "$DownloadURL"
        unzip -o "downloads/$DownloadFile" -x "*server.properties*" "*permissions.json*" "*whitelist.json*"
    fi
fi

**Comment by TheRemote** [comment]
The script will automatically update you to the latest Bedrock version automatically!
