### ISSUE TITLE
idea: restructure setup script into two parts: sudo commands and non-sudo commands

### ISSUE THREAD

**Issue by simondorfman** [TheRemote/MinecraftBedrockServer#46]
I like how this [tutorial](https://linuxize.com/post/how-to-install-minecraft-server-on-raspberry-pi/#creating-minecraft-user) suggests running the bedrock server under a separate, lower-privileged user, to increase security.

Perhaps the same thing could be achieved with MinecraftBedrockServer? Perhaps by separating the parts that require sudo into a separate script? Then, this could be installed in two parts, one script (the sudo commands) by a more privileged user, and the rest of the commands by a less privileged user.

I tried to get this working, but got stuck and gave up for now. But I thought I'd share this idea, in case anyone else wants to give it a shot. And also, to see if y'all think it would actually increase security and be worth the hassle.

**Comment by aghadjip** [comment]
Hey Simon, are you running start.sh as super user? Sudo is needed for the setupminecraft.sh script as it needs to install packages and setup the server service, Otherwise if you start it with the service or run ./start.sh it starts it as the unprivileged user. once installed sudo is not needed to start/restart/stop the minecraft server

**Comment by TheRemote** [comment]
Script has been updated to make this more clear.  Thanks!
