### ISSUE TITLE
raspberry pi 4 missing ld-linux-x86-64 issue

### ISSUE THREAD

**Issue by foloinfo** [TheRemote/MinecraftBedrockServer#47]
It seems like the raspberry pi setup is broken.
After the setup complete it fails to start on Raspberry Pi 4.

```
Setup is complete.  Starting Minecraft server...
Minecraft server failed to start after 20 seconds.
There is no screen to be resumed matching test.
```

`tail /logs/xxx.log` says

```
/lib64/ld-linux-x86-64.so.2: No such file or directory
```

Am I missing something?

**Comment by TheRemote** [comment]
Hey foloinfo,

It has been a long time since I did the Raspberry Pi portion of this piece since it was deemed too slow to be worth it at the time.  It hasn't been tried on the new 64 bit Raspbian though or on the newest models of Pi.

This error is saying it can't find the ld-linux library.  This is likely because there is a pre-packaged set of binaries included in here which by now are very outdated.  You'd have to get a newer updated set of x86_64 binaries (I think I outlined how to do this somewhere, I'd have to check my notes to even remember now).  

It would probably be worth trying again to see if any of the hardware and software advancements have changed the prospects of whether it's possible to run a playable server using the native x86_64 binaries on the Raspberry Pi.  

To give you an idea of how slow it was before, you would usually time out joining the server before the map could load.  So not like, a little slow, like you have to try logging in a bunch of times to not time out before the map loads slow.

This was years ago though now.  I will update the README of the project to reflect this reality, but this is something I'd like to revisit.  If I go through the process to grab the needed binaries again for emulation will it be fast enough now to actually log in and move around?

**Comment by kocicky** [comment]
try ls -l /lib64/ld-linux-x86-64.so.2
Mine was linking to missing file (because it exist but it's not a file but symbolic link):
lrwxrwxrwx 1 root root 45 Dec 13 10:23 ld-linux-x86-64.so.2 -> /home/ubuntu/minecraftbe/libecraft/ld-2.28.so
so you must find the right file
ls /home/ubuntu/minecraftbe/libecraft
mine file was ld-2.31.so
so you must change symlink:
sudo ln -sfn /home/ubuntu/minecraftbe/libecraft/ld-2.31.so /lib64/ld-linux-x86-64.so.2
and then change rights:
sudo chmod ugo+x /lib64/ld-linux-x86-64.so.2
now you can start bedrock server
