### ISSUE TITLE
Is this project dead? 

### ISSUE THREAD

**Issue by pogzie** [TheRemote/MinecraftBedrockServer#49]
Piles of issues, bunch of PRs. I happen to pass by here due to a problem I have saying that my server is outdated even if im using the latest version with the hopes that there was a change to parse the download correctly. 

Is there any active fork for this?

**Comment by TheRemote** [comment]
> Is this project dead?

No.  I recently was on a couple of months ago, but just to be sure I just downloaded the current version of the SetupMinecraft.sh script onto a Ubuntu 20.04 server and it correctly parsed and downloaded the latest version.

The way I wrote this makes it always download the latest version that they have published on their web site.  It's likely that they released a new version but were either slow at updating the web site's official server download or perhaps web caching / other shenanigans were at play.

I may be behind on pull requests and features but it has been a busy and crazy year, but as far as I am aware it has remained functional for what it is and I hope to clean some of those up here in the near future.

Can you give us an update if it's working now?  I'm guessing that the download issue is fixed now since I was able to roll a new server here.

**Comment by TheRemote** [comment]
I found another problem that may have been related to this.  Minecraft.net made a change where the --spider parameter was returning a 503,

I've committed the change on here now to fix this by removing the spider parameter.  If you try the latest version and it isn't working let us know.
