### ISSUE TITLE
start.sh Auto Update Broken

### ISSUE THREAD

**Issue by LeseulNick** [TheRemote/MinecraftBedrockServer#66]
`# Test internet connectivity first
wget --spider --quiet https://minecraft.net/en-us/download/server/bedrock/`
results in: "HTTP request sent, awaiting response... 503 Service Unavailable
Remote file does not exist -- broken link!!!"

`# Download server index.html to check latest version
    wget -O downloads/version.html https://minecraft.net/en-us/download/server/bedrock/`
result in: "downloads/version.html: No such file or directory"

Auto-update fails and although server will restart correctly, clients will be unable to connect to it.

**Comment by TheRemote** [comment]
Hey LeseulNick,

Make sure you update to the latest version.  The problem is the "--spider" parameter.  Mojang added something on their backend that detected that and returns and error if a spider hits the web site.

The new updated version that has been out for a while now takes care of this so if you haven't already go ahead and give it an update!
