### ISSUE TITLE
Two Minecraft server instances on same machine -- one does not start with libcurl error

### ISSUE THREAD

**Issue by XPav** [TheRemote/MinecraftBedrockServer#79]
I have a survival and a creative server on the same machine, different ports.  These used to work.  

Linux PAUMA 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Other than #78 (which I found myself), at this point, I have one server working (on port 19136), but the one on port 19132 does not start.

Manually starting the server gets me:

```
alex@PAUMA:~/minecraftbe/PavloffSurvival$  /bin/bash -c "LD_LIBRARY_PATH=/home/alex/minecraftbe/PavloffSurvival /home/alex/minecraftbe/PavloffSurvival/bedrock_server"
NO LOG FILE! - setting up server logging...
[2021-04-23 10:05:52 INFO] Starting Server
[2021-04-23 10:05:52 INFO] Version 1.16.221.01
[2021-04-23 10:05:52 INFO] Session ID 8bf153da-b658-46ec-9fea-363545402679
[2021-04-23 10:05:52 ERROR] Unknown authority mode true, expected one of [ 'client-auth', 'server-auth', 'server-auth-with-rewind' ]
[2021-04-23 10:05:52 INFO] Level Name: Bedrock level
[2021-04-23 10:05:52 INFO] Game mode: 0 Survival
[2021-04-23 10:05:52 INFO] Difficulty: 1 EASY
[INFO] opening worlds/Bedrock level/db
[INFO] IPv4 supported, port: 0
[INFO] IPv6 supported, port: 0
[INFO] Package: com.mojang.minecraft.dedicatedserver
Version: 1.16.221.01
OS: Linux
Server start: 2021-04-23 10:05:52 PDT
Dmp timestamp: 2021-04-23 10:05:53 PDT
Upload Date: 2021-04-23 10:05:53 PDT
Session ID: 8bf153da-b658-46ec-9fea-363545402679
Commit hash: 29f5ac44317033b48a154d0e9ac51db5ce2d6805
Build id: 5873168
CrashReporter Key: cde4f889-d10f-3b59-87db-db348dfcb15c

Crash
[INFO]
Failed to open curl lib from binary, use libcurl.so instead
68ebb74b-7ff4-44c1-aec8-6982cb7f25dfalex@PAUMA:~/minecraftbe/PavloffSurvival$
```

But the other instance works just fine.  Is this #70 or something different?  (But it worked before?)

**Comment by murkyl** [comment]
Due to a bug the Bedrock server ALWAYS tries to open port 19132 even if you set the server port to something else. In your case, I think the server on 19136 is starting first and it is taking both 19136 and 19132. When you try and start the second server instance the port is already taken and it fails the libcurl error you see above.

Simple solution, never use 19132 and always define a different port number.
More convoluted solution if you really want to have a server that uses 19132 and you have multiple servers running AND you cannot guarantee which order they will start is to reserve the port 19132 until the server you want to use that port starts up. 

The following shell script will reserve port 19132 indefinitely. Run this script in your start.sh before everything else and none of the servers will be able to reserve 191932.

```
#!/bin/bash
PORT_ACTIVE=`netstat -lu | grep 19132`
if [ $? == 0 ] ; then
  echo "Port 19132 already in use"
else
  echo "Port 19132 inactive. Reserving UDP port indefinitely"
  nohup python3 -c "import signal;from socket import *;s1=socket(AF_INET,SOCK_DGRAM);s1.bind(('0.0.0.0',19132));signal.pause();" &
fi
```

In the server that you want to use 19132 you can run this to make sure any existing port grab is killed:
```
pkill -f "python3 -c import signal"
```

**Comment by XPav** [comment]
Yup, switched to a different port and it's all good.   

Talk about a misleading error.
