### ISSUE TITLE
Raspberry Pi 4b 

### ISSUE THREAD

**Issue by CobraBitYou** [TheRemote/MinecraftBedrockServer#81]
Upon finishing the setup, I noticed that the server screen immediately terminated. So, I tested it by running `./bedrock_server` and I get this output:

```
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
./bedrock_server: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory
```

Is this happening to anyone else? I'm running a SMB server on my RPi, so I was thinking it could be because of that.

Edit: Your scripts works perfectly on the latest version of Ubuntu desktop. I've added some of my own scripts to automate other things.

**Comment by IBXCODECAT** [comment]
can you share those scripts?

**Comment by CobraBitYou** [comment]
> can you share those scripts?

I was actually going to start a GitHub project for them, I need to make them have variables for each unique system though.

**Comment by TheRemote** [comment]
Definitely check out https://jamesachambers.com/official-minecraft-bedrock-dedicated-server-on-raspberry-pi/ for trying to do this on the Pi.

The dependencies need to be regenerated because they change a lot.  I have done this recently so you should be able to get it going but it's definitely emulation.  The guide will help get these all going!
