### ISSUE TITLE
exiting on ubuntu 18.04 without sudo command

### ISSUE THREAD

**Issue by TKTDTGT** [TheRemote/MinecraftBedrockServer#86]
"Minecraft Bedrock Server installation script by James Chambers
Latest version always at https://github.com/TheRemote/MinecraftBedrockServer
Don't forget to set up port forwarding on your router!  The default port is 19132
This script is not meant to be ran as root or sudo.  Please run normally with ./SetupMinecraft.sh.  If you know what you are doing and want to override this edit this check out of SetupMinecraft.sh.  Exiting..."

Show this on Ubuntu 18.04 using root account without sudo command.

**Comment by sparagi** [comment]
This is intended behavior.  Here is the relevant part of the error message, **emphasis** mine:

"**This script is not meant to be ran as root** or sudo."

However, the instructions for what to do instead ("Please run normally") are unclear for new admins, who may not be aware that _being root & running a command_ and _running a command using sudo_ are very similar.  Like the OP, they don't have enough context information to guess that "please run normally" means "please run as a user who isn't root".

I suggest this error message instead:

This script is not meant to be run as root. Please run ./SetupMinecraft.sh as a non-root user, without sudo; the script will call sudo when it is needed.

I would remove the instructions "for those who know what they are doing"; anyone who needs to run SetupMinecraft.sh as root will think of deleting the check.  And if they do delete the check, they will also need to make other changes, like not automatically overwriting their changes with the latest version of the script.  Since it is not reasonable to list everything they might need to change, and the scripts seem well-documented, I think it is reasonable to leave these folks to their own devices.

Pull request attached.
