### ISSUE TITLE
./start.sh issue

### ISSUE THREAD

**Issue by stxdigitizing** [TheRemote/MinecraftBedrockServer#96]
This issue happens about once or twice a month. When server does scheduled reboot and runs the minecraftrm.service file it loads correctly but hangs on "Checking for the latest version or Minecraft Bedrock server" then times out. Can anyone help? 

`Jul 03 09:29:27 minecraftrm bash[2011]: Checking for the latest version of Minecraft Bedrock server ...
Jul 03 09:39:11 minecraftrm systemd[1]: minecraftrm.service: Start operation timed out. Terminating.
Jul 03 09:39:11 minecraftrm systemd[1]: minecraftrm.service: Failed with result 'timeout'.
`
Minecraft server start fine when I manually start it with ./bedrock_server from working directory.

`LINUX Version
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
`

**Comment by TheRemote** [comment]
Hello,

Go ahead and update to the latest version of the scripts:

`curl https://raw.githubusercontent.com/TheRemote/MinecraftBedrockServer/master/SetupMinecraft.sh | bash`

Don't attempt to use an old SetupMinecraft.sh as this will not download gawk (I may have to stop people from doing this programmatically).  The SetupMinecraft.sh was updated no less than 8 times yesterday alone so if this has been going on for months we can't really troubleshoot it further as about 50 things have been changed:  https://github.com/TheRemote/MinecraftBedrockServer/blob/master/README.md

I know you aren't using the latest version because it's "wget" that is hanging.  That application was removed entirely in past updates so this is for sure an old version for this to be happening.  Can you try using the latest and let me know if it's working for you?

**Comment by stxdigitizing** [comment]
Noted! I updated to the latest script and all is good. Thanks for letting me know about the change.

**Comment by TheRemote** [comment]
Awesome!  When I originally wrote it things didn't move so quickly so I updated the instructions to just always run the live version with a one-liner.  

Thanks for confirming and for being a long time script user!

**Comment by LoungeFlyZ** [comment]
I am having the same issue, however updating using the curl command you gave ran, but didn't seem to fix the issue when the service is starting.

Here is the output from systemctl status

```
● wharejohnson.service - wharejohnson Minecraft Bedrock Server
   Loaded: loaded (/etc/systemd/system/wharejohnson.service; enabled; vendor preset: enabled)
   Active: failed (Result: timeout) since Fri 2021-07-09 17:07:55 UTC; 1min 27s ago
  Process: 16908 ExecStart=/bin/bash /home/azureuser/minecraftbe/wharejohnson/start.sh (code=killed, signal=TERM)

Jul 09 16:57:59 minecraft bash[16908]: worlds/Bedrock level/db/010700.ldb
Jul 09 16:57:59 minecraft bash[16908]: worlds/Bedrock level/db/010375.ldb
Jul 09 16:57:59 minecraft bash[16908]: worlds/Bedrock level/db/010993.ldb
Jul 09 16:57:59 minecraft bash[16908]: worlds/Bedrock level/db/010356.ldb
Jul 09 16:57:59 minecraft bash[16908]: worlds/Bedrock level/levelname.txt
Jul 09 16:57:59 minecraft bash[16908]: worlds/Bedrock level/level.dat_old
Jul 09 16:57:59 minecraft bash[16908]: Checking for the latest version of Minecraft Bedrock server ...
Jul 09 17:07:55 minecraft systemd[1]: wharejohnson.service: Start operation timed out. Terminating.
Jul 09 17:07:55 minecraft systemd[1]: wharejohnson.service: Failed with result 'timeout'.
Jul 09 17:07:55 minecraft systemd[1]: Failed to start wharejohnson Minecraft Bedrock Server.
```

How do I check the version of the scripts and make sure I have the latest?

**Comment by TheRemote** [comment]
Hey LougeFlyZ,

`curl https://raw.githubusercontent.com/TheRemote/MinecraftBedrockServer/master/SetupMinecraft.sh | bash`

will always update you to the latest version!
