### ISSUE TITLE
Feature Request - Add way to update to latest version of scripts

### ISSUE THREAD

**Issue by cdhagmann** [TheRemote/MinecraftBedrockServer#97]
Would it be possible to make it so that the scripts get updated daily as well so that important changes get added to existing servers?

**Comment by TheRemote** [comment]
It's possible but it would cause a tremendous amount of problems.  People often change/tweak the scripts to run on different systems/configurations or even for example when wget started freezing people commented those lines out.  

It would also create a giant botnet of computers that connect to this GitHub repository and download instructions every day and execute them without question.  That could be very bad if GitHub or my account got hacked and someone put something super malicious in there.

That is much more invasive than what this scripts asks from users right now.  You don't have to trust any of it right now and the only server it will automatically pull updates from is the official Microsoft Minecraft servers.  That's fine because theoretically if something crazy enough happened you could take them to court or do a class action lawsuit etc.  

Don't get me wrong, it would be very nice right now, most of all for me!  But there's some implications to doing this that are uncomfortable.  If you look at the changelog the script usually is pretty stable but we're going through a period where there's a ton of changes all at once because Bedrock made some changes and was doing blocking of bots and a bunch of other things all at roughly the same time. 

I'd say I'm open to it especially if things don't slow down with how often I have to update the script.  Theoretically if things stabilize you should be able to go months at a time without updates since theoretically once the script it stable it shouldn't have to change much.  Let's see if things stabilize here and this might not end up being necessary / worth it but there are definitely upsides and downsides to both approaches!

**Comment by TheRemote** [comment]
Going to close for the moment as things seem to have stabilized -- will remain open to this if circumstances change again!
